# Generated by Django 6.0.7 on 2026-07-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookauthor_book_authores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='auth',
        ),
    ]
