# Generated by Django 6.0.7 on 2026-07-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='year_foundation',
            field=models.DateField(null=True),
        ),
    ]
