# Generated by Django 6.0.7 on 2026-07-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_editorial_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
